name: Build & Deploy MyHouse24-Site

on:
  push:
    branches:
      - main


jobs:
  build-deploy:
    name: Build & Deploy MyHouse24-Site
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Package & Build
        run: |
          mvn clean 
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: li4nost/my-house-24-site:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: li4nost
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: li4nost/my-house-24-site:latest

      - name: Deploy to Docker
        run:
#          sshpass -p ${{ secrets.DEPLOY_SSH_KEY }} ssh -o StrictHostKeyChecking=no avada_slj@slj.avada-media-dev1.od.ua "sudo docker stop myhouse24-site" &&
#          sshpass -p ${{ secrets.DEPLOY_SSH_KEY }} ssh -o StrictHostKeyChecking=no avada_slj@slj.avada-media-dev1.od.ua "sudo docker rm myhouse24-site" &&
          sshpass -p ${{ secrets.DEPLOY_SSH_KEY }} ssh -o StrictHostKeyChecking=no avada_slj@slj.avada-media-dev1.od.ua "sudo docker rmi li4nost/my-house-24-site" &&
          sshpass -p ${{ secrets.DEPLOY_SSH_KEY }} ssh -o StrictHostKeyChecking=no avada_slj@slj.avada-media-dev1.od.ua "sudo docker pull li4nost/my-house-24-site:latest" &&
          sshpass -p ${{ secrets.DEPLOY_SSH_KEY }} ssh -o StrictHostKeyChecking=no avada_slj@slj.avada-media-dev1.od.ua "sudo docker run -v myhouse24an:/files --network=myhouse24an --name myhouse24-site -p 9081:8081 -d li4nost/my-house-24-site:latest"


